# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: 6b47ec733b05df8cc3bcec60e2d5f7ef
  secret_key: a30c002eeb58d601fa6c3c84de076301
  canvas_page_name:
  callback_url: http://localhost:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: dc4dea8f3f32df3b1f0a51aaba71da62
  secret_key: 0d0a2e7e1cd0bf9c9688e518f6aeb358
  canvas_page_name: 
  callback_url: www.hellopulse.com/
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
